### ISSUE TITLE
游戏运行一段时间后频繁跳出这个报错，导致游戏频繁卡顿

### ISSUE THREAD

**Issue by dlfnn** [MagicstMagoo/Magicst-Voxelmap-Refresh#7]
[09:36:24] [Render thread/INFO]: [STDERR]: (x + width) is outside of Raster
[09:36:24] [Render thread/INFO]: [STDERR]: java.awt.image.RasterFormatException: (x + width) is outside of Raster
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1240)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1203)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.util.ImageUtils.trim(ImageUtils.java:542)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.trimAndOutlineImage(Radar.java:1451)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.createAutoIconImageFromResourceLocations(Radar.java:1281)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.tryAutoIcon(Radar.java:967)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.calculateMobs(Radar.java:674)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Radar.onTickInGame(Radar.java:590)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Map.drawMinimap(Map.java:721)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:475)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:139)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:54)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.handler$fao000$onRenderGameOverlay(class_329.java:11477)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.method_1753(class_329.java:394)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:862)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1177)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:768)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:475)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[09:36:24] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

**Comment by MagicstMagoo** [comment]
https://jenkins.fantacs.de/job/VoxelMap
试这边的 /22版本

**Comment by dlfnn** [comment]
问题依然是有
我试试全部模组都禁用掉

**Comment by dlfnn** [comment]
所以说，体素地图现在不是大佬您在维护吗

**Comment by dlfnn** [comment]
> 

他们这个网址我没有找到在哪里反馈issues

**Comment by MagicstMagoo** [comment]
> > 
> 
> 他们这个网址我没有找到在哪里反馈issues

挺早前就没弄了😕
你可以去这个discord问下
https://discord.gg/d3qhnmkEUT

**Comment by dlfnn** [comment]
谢谢大佬
